### ISSUE TITLE
Freedom

### ISSUE THREAD

**Issue by ghost** [jeblister/bulma#5]
In #4 I noticed the `README` of this theme contained concepts I personally developed, and spent hundreds of hours upon to perfect. As I look at the README I can see most of the base and its feature set is After Dark reskinned with Bulma.

If you would like to continue using After Dark code please do either:

- Rework this theme as a direct fork of After Dark;
- Or apply the following license to any part of the code which uses my creative work and **boldly** link to After Dark in your README, in addition to including my ISC license in the LICENSE file in your repository. https://github.com/comfusion/after-dark/blob/master/LICENSE

/cc @digitalcraftsman @bep

**Comment by ghost** [comment]
@jeblister To save everyone a headache I updated the After Dark license to remove all licensing conditions. I'm flattered you'd use my code. Please enjoy.

**Comment by jeblister** [comment]
Hi @jhabdas ,
I really appreciate everything that you have done with `After Dark`.

Yes this theme is based on some features developed in After Dark and i create it  to port `bulma` css framwork to hugo.

I had already quoted  `After Dark` in my section Credit : As you can see in this commit [fix syntax to display all the credits](https://github.com/jeblister/bulma/commit/887103eec50591817b48cd7d140f4d1c6520da6e) it was i syntax error.

I apologize for not contacting you before now to let you know about this project. 

/cc @digitalcraftsman @bep

**Comment by ghost** [comment]
Thanks so much @jeblister! Hope you're having fun with Hugo. It's one hell of a generator. Cheers.

**Comment by digitalcraftsman** [comment]
Due to the multiple pings: how are this issues related to me and Bjørn (bep)?

**Comment by ghost** [comment]
We're all set here @digitalcraftsman. Thanks for checking in.

**Comment by ghost** [comment]
#13
